/// <reference path="../pb_data/types.d.ts" />

// A product had exactly one picture, which is enough for a card and not enough for the
// page that has to sell it. Most of these have three or four; twenty-one have one, and
// the page shows no gallery at all for those rather than an empty set of controls.
//
// `image` stays as it is: the card draws it, and a cart line keeps a copy, so it is not
// something to reshuffle for the sake of the product page.
migrate(
  (app) => {
    const products = app.findCollectionByNameOrId('products');
    products.fields.add(new JSONField({ name: 'images', maxSize: 2000 }));
    app.save(products);

    const gallery = {
      "essence-mascara-lash-princess": ["https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp"],
      "eyeshadow-palette-with-mirror": ["https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp"],
      "powder-canister": ["https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp"],
      "red-lipstick": ["https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp"],
      "red-nail-polish": ["https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp"],
      "calvin-klein-ck-one": ["https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp","https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp","https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp"],
      "chanel-coco-noir-eau-de": ["https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp","https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp","https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp"],
      "dior-j-adore": ["https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/1.webp","https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/2.webp","https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/3.webp"],
      "dolce-shine-eau-de": ["https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp","https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp","https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp"],
      "gucci-bloom-eau-de": ["https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp","https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp","https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp"],
      "annibale-colombo-bed": ["https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp","https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp","https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp"],
      "annibale-colombo-sofa": ["https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp","https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/2.webp","https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/3.webp"],
      "bedside-table-african-cherry": ["https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/1.webp","https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/2.webp","https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/3.webp"],
      "knoll-saarinen-executive-conference-chair": ["https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/1.webp","https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/2.webp","https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/3.webp"],
      "wooden-bathroom-sink-with-mirror": ["https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/1.webp","https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/2.webp","https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/3.webp"],
      "apple": ["https://cdn.dummyjson.com/product-images/groceries/apple/1.webp"],
      "beef-steak": ["https://cdn.dummyjson.com/product-images/groceries/beef-steak/1.webp"],
      "cat-food": ["https://cdn.dummyjson.com/product-images/groceries/cat-food/1.webp"],
      "chicken-meat": ["https://cdn.dummyjson.com/product-images/groceries/chicken-meat/1.webp","https://cdn.dummyjson.com/product-images/groceries/chicken-meat/2.webp"],
      "cooking-oil": ["https://cdn.dummyjson.com/product-images/groceries/cooking-oil/1.webp"],
      "decoration-swing": ["https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/1.webp","https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/2.webp","https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/3.webp"],
      "family-tree-photo-frame": ["https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/1.webp"],
      "house-showpiece-plant": ["https://cdn.dummyjson.com/product-images/home-decoration/house-showpiece-plant/1.webp","https://cdn.dummyjson.com/product-images/home-decoration/house-showpiece-plant/2.webp","https://cdn.dummyjson.com/product-images/home-decoration/house-showpiece-plant/3.webp"],
      "plant-pot": ["https://cdn.dummyjson.com/product-images/home-decoration/plant-pot/1.webp","https://cdn.dummyjson.com/product-images/home-decoration/plant-pot/2.webp","https://cdn.dummyjson.com/product-images/home-decoration/plant-pot/3.webp","https://cdn.dummyjson.com/product-images/home-decoration/plant-pot/4.webp"],
      "table-lamp": ["https://cdn.dummyjson.com/product-images/home-decoration/table-lamp/1.webp"],
      "bamboo-spatula": ["https://cdn.dummyjson.com/product-images/kitchen-accessories/bamboo-spatula/1.webp"],
      "black-aluminium-cup": ["https://cdn.dummyjson.com/product-images/kitchen-accessories/black-aluminium-cup/1.webp","https://cdn.dummyjson.com/product-images/kitchen-accessories/black-aluminium-cup/2.webp"],
      "black-whisk": ["https://cdn.dummyjson.com/product-images/kitchen-accessories/black-whisk/1.webp"],
      "boxed-blender": ["https://cdn.dummyjson.com/product-images/kitchen-accessories/boxed-blender/1.webp","https://cdn.dummyjson.com/product-images/kitchen-accessories/boxed-blender/2.webp","https://cdn.dummyjson.com/product-images/kitchen-accessories/boxed-blender/3.webp","https://cdn.dummyjson.com/product-images/kitchen-accessories/boxed-blender/4.webp"],
      "carbon-steel-wok": ["https://cdn.dummyjson.com/product-images/kitchen-accessories/carbon-steel-wok/1.webp"],
      "apple-macbook-pro-14-inch-space-grey": ["https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/1.webp","https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/2.webp","https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/3.webp"],
      "asus-zenbook-pro-dual-screen-laptop": ["https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/1.webp","https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/2.webp","https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/3.webp"],
      "huawei-matebook-x-pro": ["https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/1.webp","https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/2.webp","https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/3.webp"],
      "lenovo-yoga-920": ["https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/1.webp","https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/2.webp","https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/3.webp"],
      "new-dell-xps-13-9300-laptop": ["https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/1.webp","https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/2.webp","https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/3.webp"],
      "blue-black-check-shirt": ["https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/1.webp","https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/2.webp","https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/3.webp","https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/4.webp"],
      "gigabyte-aorus-men-tshirt": ["https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/1.webp","https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/2.webp","https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/3.webp","https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/4.webp"],
      "man-plaid-shirt": ["https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/1.webp","https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/2.webp","https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/3.webp","https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/4.webp"],
      "man-short-sleeve-shirt": ["https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/1.webp","https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/2.webp","https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/3.webp","https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/4.webp"],
      "men-check-shirt": ["https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/1.webp","https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/2.webp","https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/3.webp","https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/4.webp"],
      "nike-air-jordan-1-red-and-black": ["https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/1.webp","https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/2.webp","https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/3.webp","https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/4.webp"],
      "nike-baseball-cleats": ["https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/1.webp","https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/2.webp","https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/3.webp","https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/4.webp"],
      "puma-future-rider-trainers": ["https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/1.webp","https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/2.webp","https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/3.webp","https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/4.webp"],
      "sports-sneakers-off-white-red": ["https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/1.webp","https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/2.webp","https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/3.webp","https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/4.webp"],
      "sports-sneakers-off-white-red-2": ["https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/1.webp","https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/2.webp","https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/3.webp","https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/4.webp"],
      "brown-leather-belt-watch": ["https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/1.webp","https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/2.webp","https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/3.webp"],
      "longines-master-collection": ["https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/1.webp","https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/2.webp","https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/3.webp"],
      "rolex-cellini-date-black-dial": ["https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/1.webp","https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/2.webp","https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/3.webp"],
      "rolex-cellini-moonphase": ["https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/1.webp","https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/2.webp","https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/3.webp"],
      "rolex-datejust": ["https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/1.webp","https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/2.webp","https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/3.webp"],
      "amazon-echo-plus": ["https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/1.webp","https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/2.webp"],
      "apple-airpods": ["https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/1.webp","https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/2.webp","https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/3.webp"],
      "apple-airpods-max-silver": ["https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/1.webp"],
      "apple-airpower-wireless-charger": ["https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/1.webp"],
      "apple-homepod-mini-cosmic-grey": ["https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/1.webp"],
      "generic-motorcycle": ["https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/1.webp","https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/2.webp","https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/3.webp","https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/4.webp"],
      "kawasaki-z800": ["https://cdn.dummyjson.com/product-images/motorcycle/kawasaki-z800/1.webp","https://cdn.dummyjson.com/product-images/motorcycle/kawasaki-z800/2.webp","https://cdn.dummyjson.com/product-images/motorcycle/kawasaki-z800/3.webp","https://cdn.dummyjson.com/product-images/motorcycle/kawasaki-z800/4.webp"],
      "motogp-ci-h1": ["https://cdn.dummyjson.com/product-images/motorcycle/motogp-ci.h1/1.webp","https://cdn.dummyjson.com/product-images/motorcycle/motogp-ci.h1/2.webp","https://cdn.dummyjson.com/product-images/motorcycle/motogp-ci.h1/3.webp","https://cdn.dummyjson.com/product-images/motorcycle/motogp-ci.h1/4.webp"],
      "scooter-motorcycle": ["https://cdn.dummyjson.com/product-images/motorcycle/scooter-motorcycle/1.webp","https://cdn.dummyjson.com/product-images/motorcycle/scooter-motorcycle/2.webp","https://cdn.dummyjson.com/product-images/motorcycle/scooter-motorcycle/3.webp","https://cdn.dummyjson.com/product-images/motorcycle/scooter-motorcycle/4.webp"],
      "sportbike-motorcycle": ["https://cdn.dummyjson.com/product-images/motorcycle/sportbike-motorcycle/1.webp","https://cdn.dummyjson.com/product-images/motorcycle/sportbike-motorcycle/2.webp","https://cdn.dummyjson.com/product-images/motorcycle/sportbike-motorcycle/3.webp","https://cdn.dummyjson.com/product-images/motorcycle/sportbike-motorcycle/4.webp"],
      "iphone-5s": ["https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/1.webp","https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/2.webp","https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/3.webp"],
      "iphone-6": ["https://cdn.dummyjson.com/product-images/smartphones/iphone-6/1.webp","https://cdn.dummyjson.com/product-images/smartphones/iphone-6/2.webp","https://cdn.dummyjson.com/product-images/smartphones/iphone-6/3.webp"],
      "iphone-13-pro": ["https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/1.webp","https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/2.webp","https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/3.webp"],
      "iphone-x": ["https://cdn.dummyjson.com/product-images/smartphones/iphone-x/1.webp","https://cdn.dummyjson.com/product-images/smartphones/iphone-x/2.webp","https://cdn.dummyjson.com/product-images/smartphones/iphone-x/3.webp"],
      "oppo-a57": ["https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/1.webp","https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/2.webp","https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/3.webp"],
      "american-football": ["https://cdn.dummyjson.com/product-images/sports-accessories/american-football/1.webp"],
      "baseball-ball": ["https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/1.webp"],
      "baseball-glove": ["https://cdn.dummyjson.com/product-images/sports-accessories/baseball-glove/1.webp","https://cdn.dummyjson.com/product-images/sports-accessories/baseball-glove/2.webp","https://cdn.dummyjson.com/product-images/sports-accessories/baseball-glove/3.webp"],
      "basketball": ["https://cdn.dummyjson.com/product-images/sports-accessories/basketball/1.webp"],
      "basketball-rim": ["https://cdn.dummyjson.com/product-images/sports-accessories/basketball-rim/1.webp"],
      "black-sun-glasses": ["https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/1.webp","https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/2.webp","https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/3.webp"],
      "classic-sun-glasses": ["https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/1.webp","https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/2.webp","https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/3.webp"],
      "green-and-black-glasses": ["https://cdn.dummyjson.com/product-images/sunglasses/green-and-black-glasses/1.webp","https://cdn.dummyjson.com/product-images/sunglasses/green-and-black-glasses/2.webp","https://cdn.dummyjson.com/product-images/sunglasses/green-and-black-glasses/3.webp"],
      "party-glasses": ["https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/1.webp","https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/2.webp","https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/3.webp"],
      "sunglasses": ["https://cdn.dummyjson.com/product-images/sunglasses/sunglasses/1.webp","https://cdn.dummyjson.com/product-images/sunglasses/sunglasses/2.webp","https://cdn.dummyjson.com/product-images/sunglasses/sunglasses/3.webp"],
      "blue-frock": ["https://cdn.dummyjson.com/product-images/tops/blue-frock/1.webp","https://cdn.dummyjson.com/product-images/tops/blue-frock/2.webp","https://cdn.dummyjson.com/product-images/tops/blue-frock/3.webp","https://cdn.dummyjson.com/product-images/tops/blue-frock/4.webp"],
      "girl-summer-dress": ["https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/1.webp","https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/2.webp","https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/3.webp","https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/4.webp"],
      "gray-dress": ["https://cdn.dummyjson.com/product-images/tops/gray-dress/1.webp","https://cdn.dummyjson.com/product-images/tops/gray-dress/2.webp","https://cdn.dummyjson.com/product-images/tops/gray-dress/3.webp","https://cdn.dummyjson.com/product-images/tops/gray-dress/4.webp"],
      "short-frock": ["https://cdn.dummyjson.com/product-images/tops/short-frock/1.webp","https://cdn.dummyjson.com/product-images/tops/short-frock/2.webp","https://cdn.dummyjson.com/product-images/tops/short-frock/3.webp","https://cdn.dummyjson.com/product-images/tops/short-frock/4.webp"],
      "tartan-dress": ["https://cdn.dummyjson.com/product-images/tops/tartan-dress/1.webp","https://cdn.dummyjson.com/product-images/tops/tartan-dress/2.webp","https://cdn.dummyjson.com/product-images/tops/tartan-dress/3.webp","https://cdn.dummyjson.com/product-images/tops/tartan-dress/4.webp"],
      "300-touring": ["https://cdn.dummyjson.com/product-images/vehicle/300-touring/1.webp","https://cdn.dummyjson.com/product-images/vehicle/300-touring/2.webp","https://cdn.dummyjson.com/product-images/vehicle/300-touring/3.webp","https://cdn.dummyjson.com/product-images/vehicle/300-touring/4.webp","https://cdn.dummyjson.com/product-images/vehicle/300-touring/5.webp","https://cdn.dummyjson.com/product-images/vehicle/300-touring/6.webp"],
      "charger-sxt-rwd": ["https://cdn.dummyjson.com/product-images/vehicle/charger-sxt-rwd/1.webp","https://cdn.dummyjson.com/product-images/vehicle/charger-sxt-rwd/2.webp","https://cdn.dummyjson.com/product-images/vehicle/charger-sxt-rwd/3.webp","https://cdn.dummyjson.com/product-images/vehicle/charger-sxt-rwd/4.webp","https://cdn.dummyjson.com/product-images/vehicle/charger-sxt-rwd/5.webp","https://cdn.dummyjson.com/product-images/vehicle/charger-sxt-rwd/6.webp"],
      "dodge-hornet-gt-plus": ["https://cdn.dummyjson.com/product-images/vehicle/dodge-hornet-gt-plus/1.webp","https://cdn.dummyjson.com/product-images/vehicle/dodge-hornet-gt-plus/2.webp","https://cdn.dummyjson.com/product-images/vehicle/dodge-hornet-gt-plus/3.webp","https://cdn.dummyjson.com/product-images/vehicle/dodge-hornet-gt-plus/4.webp","https://cdn.dummyjson.com/product-images/vehicle/dodge-hornet-gt-plus/5.webp","https://cdn.dummyjson.com/product-images/vehicle/dodge-hornet-gt-plus/6.webp"],
      "durango-sxt-rwd": ["https://cdn.dummyjson.com/product-images/vehicle/durango-sxt-rwd/1.webp","https://cdn.dummyjson.com/product-images/vehicle/durango-sxt-rwd/2.webp","https://cdn.dummyjson.com/product-images/vehicle/durango-sxt-rwd/3.webp","https://cdn.dummyjson.com/product-images/vehicle/durango-sxt-rwd/4.webp","https://cdn.dummyjson.com/product-images/vehicle/durango-sxt-rwd/5.webp","https://cdn.dummyjson.com/product-images/vehicle/durango-sxt-rwd/6.webp"],
      "pacifica-touring": ["https://cdn.dummyjson.com/product-images/vehicle/pacifica-touring/1.webp","https://cdn.dummyjson.com/product-images/vehicle/pacifica-touring/2.webp","https://cdn.dummyjson.com/product-images/vehicle/pacifica-touring/3.webp","https://cdn.dummyjson.com/product-images/vehicle/pacifica-touring/4.webp","https://cdn.dummyjson.com/product-images/vehicle/pacifica-touring/5.webp","https://cdn.dummyjson.com/product-images/vehicle/pacifica-touring/6.webp"],
      "blue-women-s-handbag": ["https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/1.webp","https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/2.webp","https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/3.webp"],
      "heshe-women-s-leather-bag": ["https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/1.webp","https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/2.webp","https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/3.webp"],
      "prada-women-bag": ["https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/1.webp","https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/2.webp","https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/3.webp"],
      "white-faux-leather-backpack": ["https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/1.webp","https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/2.webp","https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/3.webp"],
      "women-handbag-black": ["https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/1.webp","https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/2.webp","https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/3.webp"],
      "black-women-s-gown": ["https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/1.webp","https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/2.webp","https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/3.webp","https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/4.webp"],
      "corset-leather-with-skirt": ["https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/1.webp","https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/2.webp","https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/3.webp","https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/4.webp"],
      "corset-with-black-skirt": ["https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/1.webp","https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/2.webp","https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/3.webp","https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/4.webp"],
      "dress-pea": ["https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/1.webp","https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/2.webp","https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/3.webp","https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/4.webp"],
      "marni-red-black-suit": ["https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/1.webp","https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/2.webp","https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/3.webp","https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/4.webp"],
      "black-brown-slipper": ["https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/1.webp","https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/2.webp","https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/3.webp","https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/4.webp"],
      "calvin-klein-heel-shoes": ["https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/1.webp","https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/2.webp","https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/3.webp","https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/4.webp"],
      "golden-shoes-woman": ["https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/1.webp","https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/2.webp","https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/3.webp","https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/4.webp"],
      "pampi-shoes": ["https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/1.webp","https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/2.webp","https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/3.webp","https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/4.webp"],
      "red-shoes": ["https://cdn.dummyjson.com/product-images/womens-shoes/red-shoes/1.webp","https://cdn.dummyjson.com/product-images/womens-shoes/red-shoes/2.webp","https://cdn.dummyjson.com/product-images/womens-shoes/red-shoes/3.webp","https://cdn.dummyjson.com/product-images/womens-shoes/red-shoes/4.webp"],
      "iwc-ingenieur-automatic-steel": ["https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/1.webp","https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/2.webp","https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/3.webp"],
      "rolex-cellini-moonphase-2": ["https://cdn.dummyjson.com/product-images/womens-watches/rolex-cellini-moonphase/1.webp","https://cdn.dummyjson.com/product-images/womens-watches/rolex-cellini-moonphase/2.webp","https://cdn.dummyjson.com/product-images/womens-watches/rolex-cellini-moonphase/3.webp"],
      "rolex-datejust-women": ["https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/1.webp","https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/2.webp","https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/3.webp"],
      "watch-gold-for-women": ["https://cdn.dummyjson.com/product-images/womens-watches/watch-gold-for-women/1.webp","https://cdn.dummyjson.com/product-images/womens-watches/watch-gold-for-women/2.webp","https://cdn.dummyjson.com/product-images/womens-watches/watch-gold-for-women/3.webp"],
      "women-s-wrist-watch": ["https://cdn.dummyjson.com/product-images/womens-watches/women's-wrist-watch/1.webp","https://cdn.dummyjson.com/product-images/womens-watches/women's-wrist-watch/2.webp","https://cdn.dummyjson.com/product-images/womens-watches/women's-wrist-watch/3.webp"],
    };

    for (const handle in gallery) {
      const record = app.findFirstRecordByData('products', 'handle', handle);
      record.set('images', gallery[handle]);
      app.save(record);
    }
  },
  (app) => {
    const products = app.findCollectionByNameOrId('products');
    products.fields.removeByName('images');
    return app.save(products);
  },
);
