/// <reference path="../pb_data/types.d.ts" />

// The catalogue itself: 21 categories, 5 products each, 105 records written out rather
// than fetched. A migration that reaches for the network fails when somebody else's server is
// down, and a demo whose catalogue depends on dummyjson staying up is not a demo that survives.
//
// Even 5 per category, so no category looks like the shop and no category looks abandoned.
// Three are missing — skin-care, tablets, womens-jewellery — because the source has only
// three products in each, and matching them would have cut every other category to three.
//
// Prices are cents. The amounts are dummyjson's own, relabelled as euros rather than converted —
// they were invented to begin with, and a made-up number times an exchange rate is still made up.
// regular_price_cents is there only where the source carried a discount, and is the price that
// discount implies, never one anybody paid.
migrate(
  (app) => {
    const collection = app.findCollectionByNameOrId('products');

    const rows = [
      {"handle":"essence-mascara-lash-princess","title":"Essence Mascara Lash Princess","brand":"Essence","category":"beauty","price_cents":999,"currency":"EUR","stock":99,"rating":2.56,"tags":["beauty","mascara"],"image":"https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp","regular_price_cents":1116},
      {"handle":"eyeshadow-palette-with-mirror","title":"Eyeshadow Palette with Mirror","brand":"Glamour Beauty","category":"beauty","price_cents":1999,"currency":"EUR","stock":34,"rating":2.86,"tags":["beauty","eyeshadow"],"image":"https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp","regular_price_cents":2443},
      {"handle":"powder-canister","title":"Powder Canister","brand":"Velvet Touch","category":"beauty","price_cents":1499,"currency":"EUR","stock":89,"rating":4.64,"tags":["beauty","face powder"],"image":"https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp","regular_price_cents":1663},
      {"handle":"red-lipstick","title":"Red Lipstick","brand":"Chic Cosmetics","category":"beauty","price_cents":1299,"currency":"EUR","stock":91,"rating":4.36,"tags":["beauty","lipstick"],"image":"https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp","regular_price_cents":1479},
      {"handle":"red-nail-polish","title":"Red Nail Polish","brand":"Nail Couture","category":"beauty","price_cents":899,"currency":"EUR","stock":79,"rating":4.32,"tags":["beauty","nail polish"],"image":"https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp","regular_price_cents":1015},
      {"handle":"calvin-klein-ck-one","title":"Calvin Klein CK One","brand":"Calvin Klein","category":"fragrances","price_cents":4999,"currency":"EUR","stock":29,"rating":4.37,"tags":["fragrances","perfumes"],"image":"https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp","regular_price_cents":5095},
      {"handle":"chanel-coco-noir-eau-de","title":"Chanel Coco Noir Eau De","brand":"Chanel","category":"fragrances","price_cents":12999,"currency":"EUR","stock":58,"rating":4.26,"tags":["fragrances","perfumes"],"image":"https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp","regular_price_cents":15570},
      {"handle":"dior-j-adore","title":"Dior J'adore","brand":"Dior","category":"fragrances","price_cents":8999,"currency":"EUR","stock":98,"rating":3.8,"tags":["fragrances","perfumes"],"image":"https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp","regular_price_cents":10552},
      {"handle":"dolce-shine-eau-de","title":"Dolce Shine Eau de","brand":"Dolce & Gabbana","category":"fragrances","price_cents":6999,"currency":"EUR","stock":4,"rating":3.96,"tags":["fragrances","perfumes"],"image":"https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp","regular_price_cents":7043},
      {"handle":"gucci-bloom-eau-de","title":"Gucci Bloom Eau de","brand":"Gucci","category":"fragrances","price_cents":7999,"currency":"EUR","stock":91,"rating":2.74,"tags":["fragrances","perfumes"],"image":"https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp","regular_price_cents":9344},
      {"handle":"annibale-colombo-bed","title":"Annibale Colombo Bed","brand":"Annibale Colombo","category":"furniture","price_cents":189999,"currency":"EUR","stock":88,"rating":4.77,"tags":["furniture","beds"],"image":"https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp","regular_price_cents":207808},
      {"handle":"annibale-colombo-sofa","title":"Annibale Colombo Sofa","brand":"Annibale Colombo","category":"furniture","price_cents":249999,"currency":"EUR","stock":60,"rating":3.92,"tags":["furniture","sofas"],"image":"https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp","regular_price_cents":292055},
      {"handle":"bedside-table-african-cherry","title":"Bedside Table African Cherry","brand":"Furniture Co.","category":"furniture","price_cents":29999,"currency":"EUR","stock":64,"rating":2.87,"tags":["furniture","bedside tables"],"image":"https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp","regular_price_cents":37077},
      {"handle":"knoll-saarinen-executive-conference-chair","title":"Knoll Saarinen Executive Conference Chair","brand":"Knoll","category":"furniture","price_cents":49999,"currency":"EUR","stock":26,"rating":4.88,"tags":["furniture","office chairs"],"image":"https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp","regular_price_cents":51025},
      {"handle":"wooden-bathroom-sink-with-mirror","title":"Wooden Bathroom Sink With Mirror","brand":"Bath Trends","category":"furniture","price_cents":79999,"currency":"EUR","stock":7,"rating":3.59,"tags":["furniture","bathroom"],"image":"https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp","regular_price_cents":87718},
      {"handle":"apple","title":"Apple","brand":"groceries","category":"groceries","price_cents":199,"currency":"EUR","stock":8,"rating":4.19,"tags":["fruits"],"image":"https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp","regular_price_cents":228},
      {"handle":"beef-steak","title":"Beef Steak","brand":"groceries","category":"groceries","price_cents":1299,"currency":"EUR","stock":86,"rating":4.47,"tags":["meat"],"image":"https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp","regular_price_cents":1437},
      {"handle":"cat-food","title":"Cat Food","brand":"groceries","category":"groceries","price_cents":899,"currency":"EUR","stock":46,"rating":3.13,"tags":["pet supplies","cat food"],"image":"https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp","regular_price_cents":994},
      {"handle":"chicken-meat","title":"Chicken Meat","brand":"groceries","category":"groceries","price_cents":999,"currency":"EUR","stock":97,"rating":3.19,"tags":["meat"],"image":"https://cdn.dummyjson.com/product-images/groceries/chicken-meat/thumbnail.webp","regular_price_cents":1158},
      {"handle":"cooking-oil","title":"Cooking Oil","brand":"groceries","category":"groceries","price_cents":499,"currency":"EUR","stock":10,"rating":4.8,"tags":["cooking essentials"],"image":"https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp","regular_price_cents":550},
      {"handle":"decoration-swing","title":"Decoration Swing","brand":"home-decoration","category":"home-decoration","price_cents":5999,"currency":"EUR","stock":47,"rating":3.16,"tags":["home decor","swing"],"image":"https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/thumbnail.webp","regular_price_cents":6696},
      {"handle":"family-tree-photo-frame","title":"Family Tree Photo Frame","brand":"home-decoration","category":"home-decoration","price_cents":2999,"currency":"EUR","stock":77,"rating":4.53,"tags":["home decor","photo frame"],"image":"https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/thumbnail.webp","regular_price_cents":3523},
      {"handle":"house-showpiece-plant","title":"House Showpiece Plant","brand":"home-decoration","category":"home-decoration","price_cents":3999,"currency":"EUR","stock":28,"rating":4.67,"tags":["home decor","artificial plants"],"image":"https://cdn.dummyjson.com/product-images/home-decoration/house-showpiece-plant/thumbnail.webp","regular_price_cents":4321},
      {"handle":"plant-pot","title":"Plant Pot","brand":"home-decoration","category":"home-decoration","price_cents":1499,"currency":"EUR","stock":59,"rating":3.01,"tags":["home decor","plant accessories"],"image":"https://cdn.dummyjson.com/product-images/home-decoration/plant-pot/thumbnail.webp","regular_price_cents":1609},
      {"handle":"table-lamp","title":"Table Lamp","brand":"home-decoration","category":"home-decoration","price_cents":4999,"currency":"EUR","stock":9,"rating":3.55,"tags":["home decor","lighting"],"image":"https://cdn.dummyjson.com/product-images/home-decoration/table-lamp/thumbnail.webp","regular_price_cents":5380},
      {"handle":"bamboo-spatula","title":"Bamboo Spatula","brand":"kitchen-accessories","category":"kitchen-accessories","price_cents":799,"currency":"EUR","stock":37,"rating":3.27,"tags":["kitchen tools","utensils"],"image":"https://cdn.dummyjson.com/product-images/kitchen-accessories/bamboo-spatula/thumbnail.webp","regular_price_cents":822},
      {"handle":"black-aluminium-cup","title":"Black Aluminium Cup","brand":"kitchen-accessories","category":"kitchen-accessories","price_cents":599,"currency":"EUR","stock":75,"rating":4.46,"tags":["drinkware","cups"],"image":"https://cdn.dummyjson.com/product-images/kitchen-accessories/black-aluminium-cup/thumbnail.webp","regular_price_cents":710},
      {"handle":"black-whisk","title":"Black Whisk","brand":"kitchen-accessories","category":"kitchen-accessories","price_cents":999,"currency":"EUR","stock":73,"rating":3.9,"tags":["kitchen tools","utensils"],"image":"https://cdn.dummyjson.com/product-images/kitchen-accessories/black-whisk/thumbnail.webp","regular_price_cents":1113},
      {"handle":"boxed-blender","title":"Boxed Blender","brand":"kitchen-accessories","category":"kitchen-accessories","price_cents":3999,"currency":"EUR","stock":9,"rating":4.56,"tags":["kitchen appliances","blenders"],"image":"https://cdn.dummyjson.com/product-images/kitchen-accessories/boxed-blender/thumbnail.webp","regular_price_cents":4312},
      {"handle":"carbon-steel-wok","title":"Carbon Steel Wok","brand":"kitchen-accessories","category":"kitchen-accessories","price_cents":2999,"currency":"EUR","stock":40,"rating":4.05,"tags":["cookware","woks"],"image":"https://cdn.dummyjson.com/product-images/kitchen-accessories/carbon-steel-wok/thumbnail.webp","regular_price_cents":3209},
      {"handle":"apple-macbook-pro-14-inch-space-grey","title":"Apple MacBook Pro 14 Inch Space Grey","brand":"Apple","category":"laptops","price_cents":199999,"currency":"EUR","stock":24,"rating":3.65,"tags":["laptops","apple"],"image":"https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp","regular_price_cents":209841},
      {"handle":"asus-zenbook-pro-dual-screen-laptop","title":"Asus Zenbook Pro Dual Screen Laptop","brand":"Asus","category":"laptops","price_cents":179999,"currency":"EUR","stock":45,"rating":3.95,"tags":["laptops"],"image":"https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp","regular_price_cents":202565},
      {"handle":"huawei-matebook-x-pro","title":"Huawei Matebook X Pro","brand":"Huawei","category":"laptops","price_cents":139999,"currency":"EUR","stock":75,"rating":4.98,"tags":["laptops"],"image":"https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/thumbnail.webp","regular_price_cents":154490},
      {"handle":"lenovo-yoga-920","title":"Lenovo Yoga 920","brand":"Lenovo","category":"laptops","price_cents":109999,"currency":"EUR","stock":40,"rating":2.86,"tags":["laptops"],"image":"https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/thumbnail.webp","regular_price_cents":117709},
      {"handle":"new-dell-xps-13-9300-laptop","title":"New DELL XPS 13 9300 Laptop","brand":"Dell","category":"laptops","price_cents":149999,"currency":"EUR","stock":74,"rating":2.67,"tags":["laptops"],"image":"https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/thumbnail.webp","regular_price_cents":170241},
      {"handle":"blue-black-check-shirt","title":"Blue & Black Check Shirt","brand":"Fashion Trends","category":"mens-shirts","price_cents":2999,"currency":"EUR","stock":38,"rating":3.64,"tags":["clothing","men's shirts"],"image":"https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/thumbnail.webp","regular_price_cents":3543},
      {"handle":"gigabyte-aorus-men-tshirt","title":"Gigabyte Aorus Men Tshirt","brand":"Gigabyte","category":"mens-shirts","price_cents":2499,"currency":"EUR","stock":90,"rating":3.18,"tags":["clothing","men's t-shirts"],"image":"https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/thumbnail.webp","regular_price_cents":2523},
      {"handle":"man-plaid-shirt","title":"Man Plaid Shirt","brand":"Classic Wear","category":"mens-shirts","price_cents":3499,"currency":"EUR","stock":82,"rating":3.46,"tags":["clothing","men's shirts"],"image":"https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/thumbnail.webp","regular_price_cents":4347},
      {"handle":"man-short-sleeve-shirt","title":"Man Short Sleeve Shirt","brand":"Casual Comfort","category":"mens-shirts","price_cents":1999,"currency":"EUR","stock":2,"rating":2.9,"tags":["clothing","men's shirts"],"image":"https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp","regular_price_cents":2146},
      {"handle":"men-check-shirt","title":"Men Check Shirt","brand":"Urban Chic","category":"mens-shirts","price_cents":2799,"currency":"EUR","stock":95,"rating":2.72,"tags":["clothing","men's shirts"],"image":"https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/thumbnail.webp","regular_price_cents":3158},
      {"handle":"nike-air-jordan-1-red-and-black","title":"Nike Air Jordan 1 Red And Black","brand":"Nike","category":"mens-shoes","price_cents":14999,"currency":"EUR","stock":7,"rating":4.77,"tags":["footwear","athletic shoes"],"image":"https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/thumbnail.webp","regular_price_cents":15644},
      {"handle":"nike-baseball-cleats","title":"Nike Baseball Cleats","brand":"Nike","category":"mens-shoes","price_cents":7999,"currency":"EUR","stock":12,"rating":3.88,"tags":["footwear","sports cleats"],"image":"https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/thumbnail.webp","regular_price_cents":9760},
      {"handle":"puma-future-rider-trainers","title":"Puma Future Rider Trainers","brand":"Puma","category":"mens-shoes","price_cents":8999,"currency":"EUR","stock":90,"rating":4.9,"tags":["footwear","casual shoes"],"image":"https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp","regular_price_cents":9394},
      {"handle":"sports-sneakers-off-white-red","title":"Sports Sneakers Off White & Red","brand":"Off White","category":"mens-shoes","price_cents":11999,"currency":"EUR","stock":17,"rating":4.77,"tags":["footwear","athletic shoes"],"image":"https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp","regular_price_cents":12627},
      {"handle":"sports-sneakers-off-white-red-2","title":"Sports Sneakers Off White Red","brand":"Off White","category":"mens-shoes","price_cents":10999,"currency":"EUR","stock":62,"rating":4.69,"tags":["footwear","casual shoes"],"image":"https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp","regular_price_cents":11003},
      {"handle":"brown-leather-belt-watch","title":"Brown Leather Belt Watch","brand":"Fashion Timepieces","category":"mens-watches","price_cents":8999,"currency":"EUR","stock":32,"rating":4.19,"tags":["watches","leather watches"],"image":"https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/thumbnail.webp","regular_price_cents":9572},
      {"handle":"longines-master-collection","title":"Longines Master Collection","brand":"Longines","category":"mens-watches","price_cents":149999,"currency":"EUR","stock":100,"rating":3.87,"tags":["watches","luxury watches"],"image":"https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/thumbnail.webp","regular_price_cents":181246},
      {"handle":"rolex-cellini-date-black-dial","title":"Rolex Cellini Date Black Dial","brand":"Rolex","category":"mens-watches","price_cents":899999,"currency":"EUR","stock":40,"rating":4.97,"tags":["watches","luxury watches"],"image":"https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/thumbnail.webp","regular_price_cents":987707},
      {"handle":"rolex-cellini-moonphase","title":"Rolex Cellini Moonphase","brand":"Rolex","category":"mens-watches","price_cents":1299999,"currency":"EUR","stock":36,"rating":2.58,"tags":["watches","luxury watches"],"image":"https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/thumbnail.webp","regular_price_cents":1576138},
      {"handle":"rolex-datejust","title":"Rolex Datejust","brand":"Rolex","category":"mens-watches","price_cents":1099999,"currency":"EUR","stock":86,"rating":3.66,"tags":["watches","luxury watches"],"image":"https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/thumbnail.webp","regular_price_cents":1142619},
      {"handle":"amazon-echo-plus","title":"Amazon Echo Plus","brand":"Amazon","category":"mobile-accessories","price_cents":9999,"currency":"EUR","stock":61,"rating":4.99,"tags":["electronics","smart speakers"],"image":"https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp","regular_price_cents":11372},
      {"handle":"apple-airpods","title":"Apple Airpods","brand":"Apple","category":"mobile-accessories","price_cents":12999,"currency":"EUR","stock":67,"rating":4.15,"tags":["electronics","wireless earphones"],"image":"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp","regular_price_cents":15391},
      {"handle":"apple-airpods-max-silver","title":"Apple AirPods Max Silver","brand":"Apple","category":"mobile-accessories","price_cents":54999,"currency":"EUR","stock":59,"rating":3.47,"tags":["electronics","over-ear headphones"],"image":"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp","regular_price_cents":63708},
      {"handle":"apple-airpower-wireless-charger","title":"Apple Airpower Wireless Charger","brand":"Apple","category":"mobile-accessories","price_cents":7999,"currency":"EUR","stock":1,"rating":3.68,"tags":["electronics","wireless chargers"],"image":"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp","regular_price_cents":8374},
      {"handle":"apple-homepod-mini-cosmic-grey","title":"Apple HomePod Mini Cosmic Grey","brand":"Apple","category":"mobile-accessories","price_cents":9999,"currency":"EUR","stock":27,"rating":4.62,"tags":["electronics","smart speakers"],"image":"https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp","regular_price_cents":12209},
      {"handle":"generic-motorcycle","title":"Generic Motorcycle","brand":"Generic Motors","category":"motorcycle","price_cents":399999,"currency":"EUR","stock":34,"rating":4.91,"tags":["motorcycles"],"image":"https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/thumbnail.webp","regular_price_cents":455061},
      {"handle":"kawasaki-z800","title":"Kawasaki Z800","brand":"Kawasaki","category":"motorcycle","price_cents":899999,"currency":"EUR","stock":52,"rating":3.98,"tags":["motorcycles","sportbikes"],"image":"https://cdn.dummyjson.com/product-images/motorcycle/kawasaki-z800/thumbnail.webp","regular_price_cents":997450},
      {"handle":"motogp-ci-h1","title":"MotoGP CI.H1","brand":"MotoGP","category":"motorcycle","price_cents":1499999,"currency":"EUR","stock":10,"rating":2.97,"tags":["motorcycles","sportbikes"],"image":"https://cdn.dummyjson.com/product-images/motorcycle/motogp-ci.h1/thumbnail.webp","regular_price_cents":1611516},
      {"handle":"scooter-motorcycle","title":"Scooter Motorcycle","brand":"ScootMaster","category":"motorcycle","price_cents":299999,"currency":"EUR","stock":84,"rating":2.53,"tags":["motorcycles","scooters"],"image":"https://cdn.dummyjson.com/product-images/motorcycle/scooter-motorcycle/thumbnail.webp","regular_price_cents":320067},
      {"handle":"sportbike-motorcycle","title":"Sportbike Motorcycle","brand":"SpeedMaster","category":"motorcycle","price_cents":749999,"currency":"EUR","stock":0,"rating":3.94,"tags":["motorcycles","sportbikes"],"image":"https://cdn.dummyjson.com/product-images/motorcycle/sportbike-motorcycle/thumbnail.webp","regular_price_cents":848223},
      {"handle":"iphone-5s","title":"iPhone 5s","brand":"Apple","category":"smartphones","price_cents":19999,"currency":"EUR","stock":25,"rating":2.83,"tags":["smartphones","apple"],"image":"https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/thumbnail.webp","regular_price_cents":22964},
      {"handle":"iphone-6","title":"iPhone 6","brand":"Apple","category":"smartphones","price_cents":29999,"currency":"EUR","stock":60,"rating":3.41,"tags":["smartphones","apple"],"image":"https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp","regular_price_cents":32150},
      {"handle":"iphone-13-pro","title":"iPhone 13 Pro","brand":"Apple","category":"smartphones","price_cents":109999,"currency":"EUR","stock":56,"rating":4.12,"tags":["smartphones","apple"],"image":"https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp","regular_price_cents":121372},
      {"handle":"iphone-x","title":"iPhone X","brand":"Apple","category":"smartphones","price_cents":89999,"currency":"EUR","stock":37,"rating":2.51,"tags":["smartphones","apple"],"image":"https://cdn.dummyjson.com/product-images/smartphones/iphone-x/thumbnail.webp","regular_price_cents":111925},
      {"handle":"oppo-a57","title":"Oppo A57","brand":"Oppo","category":"smartphones","price_cents":24999,"currency":"EUR","stock":19,"rating":3.94,"tags":["smartphones","oppo"],"image":"https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/thumbnail.webp","regular_price_cents":25622},
      {"handle":"american-football","title":"American Football","brand":"sports-accessories","category":"sports-accessories","price_cents":1999,"currency":"EUR","stock":53,"rating":4.91,"tags":["sports equipment","american football"],"image":"https://cdn.dummyjson.com/product-images/sports-accessories/american-football/thumbnail.webp","regular_price_cents":2103},
      {"handle":"baseball-ball","title":"Baseball Ball","brand":"sports-accessories","category":"sports-accessories","price_cents":899,"currency":"EUR","stock":100,"rating":2.57,"tags":["sports equipment","baseball"],"image":"https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp","regular_price_cents":915},
      {"handle":"baseball-glove","title":"Baseball Glove","brand":"sports-accessories","category":"sports-accessories","price_cents":2499,"currency":"EUR","stock":22,"rating":3.96,"tags":["sports equipment","baseball"],"image":"https://cdn.dummyjson.com/product-images/sports-accessories/baseball-glove/thumbnail.webp","regular_price_cents":2574},
      {"handle":"basketball","title":"Basketball","brand":"sports-accessories","category":"sports-accessories","price_cents":1499,"currency":"EUR","stock":75,"rating":4.66,"tags":["sports equipment","basketball"],"image":"https://cdn.dummyjson.com/product-images/sports-accessories/basketball/thumbnail.webp","regular_price_cents":1619},
      {"handle":"basketball-rim","title":"Basketball Rim","brand":"sports-accessories","category":"sports-accessories","price_cents":3999,"currency":"EUR","stock":43,"rating":4.6,"tags":["sports equipment","basketball"],"image":"https://cdn.dummyjson.com/product-images/sports-accessories/basketball-rim/thumbnail.webp","regular_price_cents":4334},
      {"handle":"black-sun-glasses","title":"Black Sun Glasses","brand":"Fashion Shades","category":"sunglasses","price_cents":2999,"currency":"EUR","stock":60,"rating":4.41,"tags":["eyewear","sunglasses"],"image":"https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/thumbnail.webp","regular_price_cents":3155},
      {"handle":"classic-sun-glasses","title":"Classic Sun Glasses","brand":"Fashion Shades","category":"sunglasses","price_cents":2499,"currency":"EUR","stock":1,"rating":3.86,"tags":["eyewear","sunglasses"],"image":"https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/thumbnail.webp","regular_price_cents":2629},
      {"handle":"green-and-black-glasses","title":"Green and Black Glasses","brand":"Fashion Shades","category":"sunglasses","price_cents":3499,"currency":"EUR","stock":24,"rating":4.55,"tags":["eyewear","sunglasses"],"image":"https://cdn.dummyjson.com/product-images/sunglasses/green-and-black-glasses/thumbnail.webp","regular_price_cents":3535},
      {"handle":"party-glasses","title":"Party Glasses","brand":"Fashion Fun","category":"sunglasses","price_cents":1999,"currency":"EUR","stock":86,"rating":2.79,"tags":["eyewear","party glasses"],"image":"https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/thumbnail.webp","regular_price_cents":2252},
      {"handle":"sunglasses","title":"Sunglasses","brand":"Fashion Shades","category":"sunglasses","price_cents":2299,"currency":"EUR","stock":27,"rating":3.02,"tags":["eyewear","sunglasses"],"image":"https://cdn.dummyjson.com/product-images/sunglasses/sunglasses/thumbnail.webp","regular_price_cents":2334},
      {"handle":"blue-frock","title":"Blue Frock","brand":"tops","category":"tops","price_cents":2999,"currency":"EUR","stock":52,"rating":4.17,"tags":["clothing","dresses"],"image":"https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp","regular_price_cents":3413},
      {"handle":"girl-summer-dress","title":"Girl Summer Dress","brand":"tops","category":"tops","price_cents":1999,"currency":"EUR","stock":43,"rating":4.77,"tags":["clothing","girls' dresses"],"image":"https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/thumbnail.webp","regular_price_cents":2474},
      {"handle":"gray-dress","title":"Gray Dress","brand":"tops","category":"tops","price_cents":3499,"currency":"EUR","stock":55,"rating":2.72,"tags":["clothing","dresses"],"image":"https://cdn.dummyjson.com/product-images/tops/gray-dress/thumbnail.webp","regular_price_cents":4082},
      {"handle":"short-frock","title":"Short Frock","brand":"tops","category":"tops","price_cents":2499,"currency":"EUR","stock":22,"rating":3.23,"tags":["clothing","dresses"],"image":"https://cdn.dummyjson.com/product-images/tops/short-frock/thumbnail.webp","regular_price_cents":2887},
      {"handle":"tartan-dress","title":"Tartan Dress","brand":"tops","category":"tops","price_cents":3999,"currency":"EUR","stock":73,"rating":4.05,"tags":["clothing","dresses"],"image":"https://cdn.dummyjson.com/product-images/tops/tartan-dress/thumbnail.webp","regular_price_cents":4594},
      {"handle":"300-touring","title":"300 Touring","brand":"Chrysler","category":"vehicle","price_cents":2899999,"currency":"EUR","stock":54,"rating":4.05,"tags":["sedans","vehicles"],"image":"https://cdn.dummyjson.com/product-images/vehicle/300-touring/thumbnail.webp","regular_price_cents":3020203},
      {"handle":"charger-sxt-rwd","title":"Charger SXT RWD","brand":"Dodge","category":"vehicle","price_cents":3299999,"currency":"EUR","stock":57,"rating":2.58,"tags":["sedans","sports cars","vehicles"],"image":"https://cdn.dummyjson.com/product-images/vehicle/charger-sxt-rwd/thumbnail.webp","regular_price_cents":3595945},
      {"handle":"dodge-hornet-gt-plus","title":"Dodge Hornet GT Plus","brand":"Dodge","category":"vehicle","price_cents":2499999,"currency":"EUR","stock":82,"rating":2.65,"tags":["hatchbacks","compact cars","vehicles"],"image":"https://cdn.dummyjson.com/product-images/vehicle/dodge-hornet-gt-plus/thumbnail.webp","regular_price_cents":2567525},
      {"handle":"durango-sxt-rwd","title":"Durango SXT RWD","brand":"Dodge","category":"vehicle","price_cents":3699999,"currency":"EUR","stock":95,"rating":4.07,"tags":["suvs","vehicles"],"image":"https://cdn.dummyjson.com/product-images/vehicle/durango-sxt-rwd/thumbnail.webp","regular_price_cents":4427955},
      {"handle":"pacifica-touring","title":"Pacifica Touring","brand":"Chrysler","category":"vehicle","price_cents":3199999,"currency":"EUR","stock":53,"rating":3.62,"tags":["minivans","vehicles"],"image":"https://cdn.dummyjson.com/product-images/vehicle/pacifica-touring/thumbnail.webp","regular_price_cents":3754105},
      {"handle":"blue-women-s-handbag","title":"Blue Women's Handbag","brand":"Fashionista","category":"womens-bags","price_cents":4999,"currency":"EUR","stock":76,"rating":2.92,"tags":["fashion accessories","handbags"],"image":"https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/thumbnail.webp","regular_price_cents":6087},
      {"handle":"heshe-women-s-leather-bag","title":"Heshe Women's Leather Bag","brand":"Heshe","category":"womens-bags","price_cents":12999,"currency":"EUR","stock":99,"rating":4.92,"tags":["fashion accessories","leather bags"],"image":"https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/thumbnail.webp","regular_price_cents":13522},
      {"handle":"prada-women-bag","title":"Prada Women Bag","brand":"Prada","category":"womens-bags","price_cents":59999,"currency":"EUR","stock":75,"rating":2.71,"tags":["fashion accessories","designer bags"],"image":"https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/thumbnail.webp","regular_price_cents":69839},
      {"handle":"white-faux-leather-backpack","title":"White Faux Leather Backpack","brand":"Urban Chic","category":"womens-bags","price_cents":3999,"currency":"EUR","stock":39,"rating":3.36,"tags":["fashion accessories","backpacks"],"image":"https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/thumbnail.webp","regular_price_cents":4716},
      {"handle":"women-handbag-black","title":"Women Handbag Black","brand":"Elegance Collection","category":"womens-bags","price_cents":5999,"currency":"EUR","stock":11,"rating":2.89,"tags":["fashion accessories","handbags"],"image":"https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/thumbnail.webp","regular_price_cents":6789},
      {"handle":"black-women-s-gown","title":"Black Women's Gown","brand":"womens-dresses","category":"womens-dresses","price_cents":12999,"currency":"EUR","stock":25,"rating":3.64,"tags":["clothing","gowns"],"image":"https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/thumbnail.webp","regular_price_cents":14521},
      {"handle":"corset-leather-with-skirt","title":"Corset Leather With Skirt","brand":"womens-dresses","category":"womens-dresses","price_cents":8999,"currency":"EUR","stock":30,"rating":3.05,"tags":["clothing","corsets","skirts"],"image":"https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/thumbnail.webp","regular_price_cents":10746},
      {"handle":"corset-with-black-skirt","title":"Corset With Black Skirt","brand":"womens-dresses","category":"womens-dresses","price_cents":7999,"currency":"EUR","stock":33,"rating":4.52,"tags":["clothing","corsets","skirts"],"image":"https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/thumbnail.webp","regular_price_cents":9417},
      {"handle":"dress-pea","title":"Dress Pea","brand":"womens-dresses","category":"womens-dresses","price_cents":4999,"currency":"EUR","stock":6,"rating":4.88,"tags":["clothing","dresses"],"image":"https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/thumbnail.webp","regular_price_cents":6073},
      {"handle":"marni-red-black-suit","title":"Marni Red & Black Suit","brand":"womens-dresses","category":"womens-dresses","price_cents":17999,"currency":"EUR","stock":62,"rating":4.48,"tags":["clothing","suits"],"image":"https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/thumbnail.webp","regular_price_cents":22226},
      {"handle":"black-brown-slipper","title":"Black & Brown Slipper","brand":"Comfort Trends","category":"womens-shoes","price_cents":1999,"currency":"EUR","stock":3,"rating":2.53,"tags":["footwear","slippers"],"image":"https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/thumbnail.webp","regular_price_cents":2068},
      {"handle":"calvin-klein-heel-shoes","title":"Calvin Klein Heel Shoes","brand":"Calvin Klein","category":"womens-shoes","price_cents":7999,"currency":"EUR","stock":93,"rating":4.92,"tags":["footwear","heel shoes"],"image":"https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/thumbnail.webp","regular_price_cents":8263},
      {"handle":"golden-shoes-woman","title":"Golden Shoes Woman","brand":"Fashion Diva","category":"womens-shoes","price_cents":4999,"currency":"EUR","stock":88,"rating":3.26,"tags":["footwear","women's shoes"],"image":"https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/thumbnail.webp","regular_price_cents":5808},
      {"handle":"pampi-shoes","title":"Pampi Shoes","brand":"Pampi","category":"womens-shoes","price_cents":2999,"currency":"EUR","stock":49,"rating":3.05,"tags":["footwear","casual shoes"],"image":"https://cdn.dummyjson.com/product-images/womens-shoes/pampi-shoes/thumbnail.webp","regular_price_cents":3493},
      {"handle":"red-shoes","title":"Red Shoes","brand":"Fashion Express","category":"womens-shoes","price_cents":3499,"currency":"EUR","stock":7,"rating":3.25,"tags":["footwear","women's shoes"],"image":"https://cdn.dummyjson.com/product-images/womens-shoes/red-shoes/thumbnail.webp","regular_price_cents":4251},
      {"handle":"iwc-ingenieur-automatic-steel","title":"IWC Ingenieur Automatic Steel","brand":"IWC","category":"womens-watches","price_cents":499999,"currency":"EUR","stock":90,"rating":2.93,"tags":["watches","luxury watches"],"image":"https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/thumbnail.webp","regular_price_cents":552180},
      {"handle":"rolex-cellini-moonphase-2","title":"Rolex Cellini Moonphase","brand":"Rolex","category":"womens-watches","price_cents":1599999,"currency":"EUR","stock":52,"rating":3.83,"tags":["watches","luxury watches"],"image":"https://cdn.dummyjson.com/product-images/womens-watches/rolex-cellini-moonphase/thumbnail.webp","regular_price_cents":1668578},
      {"handle":"rolex-datejust-women","title":"Rolex Datejust Women","brand":"Rolex","category":"womens-watches","price_cents":1099999,"currency":"EUR","stock":4,"rating":2.86,"tags":["watches","luxury watches","women's watches"],"image":"https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/thumbnail.webp","regular_price_cents":1308588},
      {"handle":"watch-gold-for-women","title":"Watch Gold for Women","brand":"Fashion Gold","category":"womens-watches","price_cents":79999,"currency":"EUR","stock":0,"rating":4.24,"tags":["watches","women's watches"],"image":"https://cdn.dummyjson.com/product-images/womens-watches/watch-gold-for-women/thumbnail.webp","regular_price_cents":97966},
      {"handle":"women-s-wrist-watch","title":"Women's Wrist Watch","brand":"Fashion Co.","category":"womens-watches","price_cents":12999,"currency":"EUR","stock":12,"rating":3.52,"tags":["watches","women's watches"],"image":"https://cdn.dummyjson.com/product-images/womens-watches/women's-wrist-watch/thumbnail.webp","regular_price_cents":14873},
    ];

    for (const row of rows) {
      const record = new Record(collection);
      for (const key in row) record.set(key, row[key]);
      app.save(record);
    }
  },
  (app) => {
    for (const record of app.findAllRecords('products')) app.delete(record);
  },
);
